version: '3'

volumes:
  prometheus_data: {}
  grafana-storage: {}

networks:
  pro_graf-net:

services:

  python_app:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python_app
    volumes:
      - ./python_app:/app
    depends_on:
      - prometheus
    networks:
      - pro_graf-net
    ports:
      - "8010:8010"
    command: ["python3", "main.py"] 

  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - pro_graf-net

  grafana:
    image: grafana/grafana-enterprise:9.5.18
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_USERS_DEFAULT_THEME=light
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    env_file:
      - ./.env.grafana
    networks:
      - pro_graf-net