version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.51.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana:10.1.9
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
volumes:
  prometheus_data: {}
