FROM python:3.12.2-alpine3.19

RUN apk update && \
    apk add --no-cache gcc musl-dev libffi-dev curl lsof net-tools

RUN pip3 install --upgrade pip

WORKDIR /app
COPY ./requirements.txt /app
RUN pip3 install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH=/app

EXPOSE 8010